### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by julieng03** [d0ugal-archive/python-rfxcom#23]
Hello,

All the documentation is not accessible. I would like to control my RFY devices (Somfy blinds)

Regards,

Julien .

**Comment by d0ugal** [comment]
Yup, this project is no longer maintained or used. The GitHub organisation aims to show this, but it isn't that clear still.

**Comment by julieng03** [comment]
ok.. maybe can you tell me where can I find another lib for rfxcom which is still in development?

Thanks!

**Comment by Danielhiversen** [comment]
https://github.com/Danielhiversen/pyRFXtrx/
